# Generated by Django 5.1 on 2026-06-10 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_assurance', models.CharField(choices=[('vie', 'Assurance Vie'), ('deces_invalidite', 'Décès-Invalidité')], max_length=20)),
                ('description', models.TextField()),
                ('prime_mensuelle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_mois', models.PositiveIntegerField()),
                ('est_actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_souscription', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField()),
                ('statut', models.CharField(choices=[('active', 'Active'), ('expiree', 'Expirée'), ('resiliee', 'Résiliée')], default='active', max_length=20)),
                ('notification_envoyee', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='souscriptions', to='assurance.produitassurance')),
            ],
        ),
    ]
